  CREATE TABLE "VC_RECHNUNG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"RE_NR" VARCHAR2(30), 
	"EMPFAENGER" VARCHAR2(200), 
	"TEXT" VARCHAR2(1000), 
	"ZAHLUNGSBEDINGUNGEN" VARCHAR2(200), 
	"STATUS" VARCHAR2(20), 
	"ERSTELLT_VON" VARCHAR2(20), 
	"ERSTELLT_DATUM" DATE, 
	"ANMERKUNGEN" VARCHAR2(500), 
	"NAME" VARCHAR2(100), 
	"UST" NUMBER, 
	"UST_SATZ" NUMBER, 
	"BRUTTOSUMME" NUMBER, 
	"NETTOSUMME" NUMBER, 
	"EMAIL" VARCHAR2(60), 
	"MITGLIEDSNR" VARCHAR2(10), 
	"MITGLIED_FK" NUMBER, 
	"DL_FK" NUMBER(*,0), 
	"STRASSE" VARCHAR2(100), 
	"POSTCODE" VARCHAR2(10), 
	"CITY" VARCHAR2(100), 
	"COUNTRY_CODE" VARCHAR2(3), 
	"EMPFAENGER_ANSPRECHPARTNER" VARCHAR2(100), 
	"EMPFAENGER_ZUSATZ" VARCHAR2(100), 
	"VERSENDER" VARCHAR2(100), 
	"VERSENDER_ANSPRECHPARTNER" VARCHAR2(100), 
	"VERSENDER_STRASSE" VARCHAR2(100), 
	"VERSENDER_ZUSATZ" VARCHAR2(100), 
	"VERSENDER_POSTCODE" VARCHAR2(10), 
	"VERSENDER_CITY" VARCHAR2(100), 
	"VERSENDER_COUNTRY_CODE" VARCHAR2(3), 
	"VERSENDER_STEUER_NR" VARCHAR2(50), 
	"VERSENDER_UST_ID" VARCHAR2(50), 
	"GF_ORGANBEZEICHNUNG" VARCHAR2(100), 
	"GF_PERSON" VARCHAR2(100), 
	"GF_SITZ" VARCHAR2(100), 
	"GF_REGISTERGERICHT" VARCHAR2(50), 
	"GF_HANDELSREGISTER_NR" VARCHAR2(50), 
	"GF_BANK" VARCHAR2(50), 
	"GF_IBAN" VARCHAR2(22), 
	"GF_KONTOINHABER" VARCHAR2(50), 
	"DATUM_LEISTUNG" DATE, 
	"DATUM_FAELLIG" DATE, 
	"WAEHRUNG_CODE" VARCHAR2(5), 
	"TAX_TOTAL_AMOUNT" NUMBER, 
	"TAX_BASIS_TOTAL_AMOUNT" NUMBER, 
	"CHARGE_TOTAL_AMOUNT" NUMBER, 
	"LINE_TOTAL_AMOUNT" NUMBER, 
	"ALLOWANCE_TOTAL_AMOUNT" NUMBER, 
	"PAYMENT_TERMS" VARCHAR2(100), 
	"TAX_RATE" NUMBER, 
	"TAX_CATEGORY_CODE" VARCHAR2(10), 
	"DELIVERY_DATE" DATE, 
	"VERSENDER_GOBAL_ID" VARCHAR2(30), 
	"NOTE_1" VARCHAR2(255), 
	"NOTE_2" VARCHAR2(255), 
	"NOTE_3" VARCHAR2(255), 
	 CONSTRAINT "VC_RECHNUNG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "VC_RECHNUNG_POS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"RECHNUNG_FK" NUMBER, 
	"MENGE" NUMBER, 
	"BETRAG_EINZEL" NUMBER, 
	"EINHEIT" VARCHAR2(20), 
	"BEZEICHNUNG" VARCHAR2(500), 
	"BETRAG_SUMME" NUMBER, 
	"DATUM" DATE, 
	"ERSTELLT_AM" DATE, 
	"ERSTELLT_VON" VARCHAR2(20), 
	"REIHENFOLGE" NUMBER(20,0), 
	"TYP" VARCHAR2(20), 
	"UST_ART" VARCHAR2(10), 
	"ANMERKUNGEN" VARCHAR2(200), 
	"TAX_RATE" NUMBER, 
	"VERPACKUNG" VARCHAR2(20), 
	"TAX_CATEGORY" VARCHAR2(20), 
	"BETRAG_EINZEL_NETTO" NUMBER, 
	 CONSTRAINT "VC_RECHNUNG_POS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_VC_RECHNUNG" 
  before insert on "VC_RECHNUNG"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "VC_RECHNUNG_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 



/
ALTER TRIGGER "BI_VC_RECHNUNG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BI_VC_RECHNUNG_POS" 
  before insert on "VC_RECHNUNG_POS"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "VC_RECHNUNG_POS_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 



/
ALTER TRIGGER "BI_VC_RECHNUNG_POS" ENABLE;

   CREATE SEQUENCE  "VC_RECHNUNG_POS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2001 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "VC_RECHNUNG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3341 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;




create or replace TRIGGER "A224048"."BI_VC_RECHNUNG" 
  before insert on "VC_RECHNUNG"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "VC_RECHNUNG_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 


/
create or replace TRIGGER "A224048"."BI_VC_RECHNUNG_POS" 
  before insert on "VC_RECHNUNG_POS"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "VC_RECHNUNG_POS_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 


/